### ISSUE TITLE
How to Starting Swarm Node.

### ISSUE THREAD

**Issue by Nipol** [MainframeOS/swarmchat#4]
Hello

I just wondering "How to starting Swarm Node". SwarmChat is used WebSocket but that is not Activate from Swarm.

I'm using the option "--ws --wsorigins localhost" that looks like not completable.

can you help me?

My Onyx Public Key's 
0x0429bc33fd3a6ed50f3a7541e92b2fb1d5070748b1c0659a1033120fcccc93b3fb8ba5257642b98371f4f65b8ae6b516b2d0677faccdac8fee2a42c5479c4ea84d

**Comment by howleysv** [comment]
Hi @Nipol 

If you want to start swarmchat, you will likely need `--wsorigins '*'` to sidestep any CORS issues in the browser. Are you getting any specific error?

**Comment by Nipol** [comment]
thanks to reply @howleysv 

I tried. but there is same problem with the `--wsorigins '*'` option. And 'swarmchat' works well when starting onyx. Maybe using mainframe custom 'swarm' would make 'swarmchat' works.
Am i correct?

**Comment by Nipol** [comment]
https://github.com/MainframeHQ/erebos/issues/57
